name: Release Branch Merge
permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*" # e.g., v1.1.0, v1.2.3 (semantic versioning)

jobs:
  merge-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # full history to access all branches

      - name: Determine release branch
        run: |
          # Determine the release branch name from the tag (e.g., v1.1.0 → release/1.1.x)
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          TAG_NO_V="${TAG_NAME#v}"              # 0.0.1
          MAJOR_MINOR=$(echo $TAG_NO_V | awk -F. '{print $1"."$2}')
          RELEASE_BRANCH="release/$MAJOR_MINOR.x"
          echo "Release branch: $RELEASE_BRANCH"
          echo "RELEASE_BRANCH=$RELEASE_BRANCH" >> $GITHUB_ENV

      - name: Merge release branch into main
        run: |
          git fetch origin
          git switch main
          git merge --ff origin/$RELEASE_BRANCH
          git push origin main

      - name: Merge release branch into develop
        run: |
          git fetch origin
          git switch develop
          git merge --ff origin/$RELEASE_BRANCH
          git push origin develop
